version: '3.8'

services:
  noottools:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "3016:3016"
    environment:
      - NODE_ENV=production
      - PORT=3016
      - DATABASE_URL=${DATABASE_URL:-postgresql://localhost:5432/noottools}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3016/api/stats"]
      timeout: 10s
      interval: 30s
      retries: 3
      start_period: 40s

  # Base de datos PostgreSQL para desarrollo local
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: noottools
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: